import CardContinue from '@components/CardContinue';
import CardStepper from '@components/CardStepper';
import CollapsibleMenu from '@components/CollapsibleMenu';
// import CollapsibleMenu from '@components/CollapsibleMenu';
import type { NextPage } from 'next';
import Head from 'next/head';
import {
  campaignAnalytics,
  campaignSetup,
  campaignPlanning,
} from '../constants/campaign';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: 'flex' }}>
        <div>
          <CollapsibleMenu />
        </div>
        <div>
          <div style={{ display: 'flex', gap: '5rem' }}>
            <CardContinue
              title="Campaign Planning"
              description="Start planning your Web 3.0 Ad Campaign here!"
              stepNumber="1"
            />
            {campaignPlanning?.map((item) => (
              <CardStepper step={item.step} title={item.title} />
            ))}
          </div>
          <br />
          <div style={{ display: 'flex', gap: '5rem' }}>
            <CardContinue
              title="Campaign Setup"
              description="Set up your NFT distribution pipeline and manage real-world benefits."
              stepNumber="2"
            />
            {campaignSetup?.map((item) => (
              <CardStepper step={item.step} title={item.title} />
            ))}
          </div>
          <br />
          <div style={{ display: 'flex', gap: '5rem' }}>
            <CardContinue
              title="Campaign Analytics"
              description="Track the performance of your campaign and & analyze user behaviour."
              stepNumber="3"
            />
            {campaignAnalytics?.map((item) => (
              <CardStepper step={item.step} title={item.title} />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
